#! /bin/sh
### BEGIN INIT INFO
# Provides:		template
# Required-Start:	$local_fs $remote_fs $network $syslog
# Required-Stop:	$local_fs $remote_fs $network $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	template - Init template script
# Description:		template - Init template script
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
#DAEMON=
#DAEMON_ARGS=
NAME=template
DESC=template
PIDFILE=/var/run/template.pid

#test -x $DAEMON || exit 0
#test -x $DAEMONBOOTSTRAP || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC"
	touch $PIDFILE
	#if start-stop-daemon --start --quiet --umask 007 --pidfile $PIDFILE --chuid redis:redis --exec $DAEMON -- $DAEMON_ARGS
	#then
	#	echo "$NAME."
	#else
	#	echo "failed"
	#fi
	;;
  stop)
	echo -n "Stopping $DESC"
	#if start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON
	#then
	#	echo "$NAME."
	#else
	#	echo "failed"
	#fi
	rm -f $PIDFILE
	;;

  restart|force-reload)
	${0} stop
	${0} start
	;;
  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
